version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/pre-registration"
    schedule:
      interval: "daily"
    target-branch: "develop"
    open-pull-requests-limit: 50
  - package-ecosystem: "maven"
    directory: "/pre-registration"
    schedule:
      interval: "daily"
    target-branch: "test"
    open-pull-requests-limit: 50
