name: Detect Leaked Secrets 1

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install detect-secrets
      run: |
        pip install detect-secrets

    - name: Create baseline file
      run: |
        detect-secrets scan > .secrets.baseline

    - name: Scan for leaked secrets in PR
      run: |
        detect-secrets scan --baseline .secrets.baseline
