name: Detect Leaked Secrets 5

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install detect-secrets
      run: |
        pip install detect-secrets

    - name: Fetch base branch
      run: |
        git fetch origin +refs/heads/${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}

    - name: Generate diff
      run: |
        git diff origin/${{ github.base_ref }}...HEAD > diff.patch

    - name: Scan for leaked secrets in PR
      run: |
        detect-secrets scan diff.patch > result.txt
        if grep -q 'Secret' result.txt; then
          echo "Secrets detected!"
          cat result.txt
          exit 1
        else
          echo "No secrets detected."
        fi
