name: Detect Secrets in PR using regex

on:
  pull_request:
    branches:
        - develop
    paths:
      - '**/*'

jobs:
  detect_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Search for secrets with custom regex patterns
        run: |
          # Define regex patterns for secrets
          SECRET_PATTERNS=(
            "AIza[0-9A-Za-z-_]{35}"  # Example: Google API key
            "AKIA[0-9A-Z]{16}"        # Example: AWS Access Key
            "-----BEGIN (RSA )?PRIVATE KEY-----"  # Example: RSA private key"
            
            
          )

          # Loop through each regex pattern and search in files
          for pattern in "${SECRET_PATTERNS[@]}"; do
            echo "Searching for pattern: $pattern"
            # Use grep to search for patterns in the files
            grep -rP "$pattern" . || true  # `-r` for recursive, `-P` for Perl-compatible regex
          done

      - name: Fail if secrets found
        run: |
          # Check if any secrets were found
          if [ $? -eq 0 ]; then
            echo "Secrets detected in the PR!"
            exit 1
          else
            echo "No secrets detected."
          fi
