name: Secret Detection

on:
  pull_request:
    branches:
      - release-1.2.0

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Scan for secrets
        run: |
          # Define regex patterns for secrets
          regex_patterns=(
            'password\s*:\s*["\']?[^$][^"\']*["\']?'
            'api[_-]?key\s*:\s*["\']?[^$][^"\']*["\']?'
            'secret\s*:\s*["\']?[^$][^"\']*["\']?'
          )

          # Scan files for secrets
          for pattern in "${regex_patterns[@]}"; do
            if grep -E -r --exclude-dir={.git,.github} "$pattern" .; then
              echo "Secret detected with pattern: $pattern"
              exit 1
            fi
          done

      - name: Ignore environment secrets
        run: |
          # Define regex pattern to ignore environment secrets
          ignore_pattern='\$\{\{\s*secrets\.[A-Z_]+\s*\}\}'

          # Scan files to ensure no false positives for environment secrets
          if grep -E -r --exclude-dir={.git,.github} "$ignore_pattern" .; then
            echo "No false positives detected for environment secrets"
          else
            echo "False positive detected for environment secrets"
            exit 1
          fi
