name: TruffleHog Scan

on:
  push:
    branches:
      - develop

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run TruffleHog
        uses: trufflesecurity/trufflehog@v3.84.1
        with:
          scan: filesystem
          regex: true
