name: Detect Leaked Secrets

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install detect-secrets
      run: |
        pip install detect-secrets

    - name: Scan for leaked secrets
      run: |
        detect-secrets scan > .secrets.baseline
        detect-secrets audit .secrets.baseline
