name: Detect Leaked Secrets

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install truffleHog
      run: |
        python -m pip install --upgrade pip
        pip install truffleHog

    - name: Run truffleHog in regex mode
      run: truffleHog --regex --json .

    - name: Check for secrets
      run: |
        if truffleHog --regex --json . | grep -q '\"reason\":'; then
          echo "Secrets detected!"
          exit 1
        else
          echo "No secrets detected."
        fi