name: Detect Leaked Secrets

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  detect-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Scan for leaked secrets
      run: |
        # Define regex patterns for common secrets
        patterns=(
          'AKIA[0-9A-Z]{16}'  # AWS Access Key ID
          'aws_secret_access_key'  # AWS Secret Access Key
          '-----BEGIN RSA PRIVATE KEY-----'  # RSA private key
          '-----BEGIN OPENSSH PRIVATE KEY-----'  # OpenSSH private key
          '-----BEGIN PGP PRIVATE KEY BLOCK-----'  # PGP private key block
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}'  # Google API Key
          'AIza[0-9A-Za-z-_]{35}' ) # Google )
