name: Secret Scan with TruffleHog

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v3

      - name: Scan for Secrets with TruffleHog
        uses: trufflesecurity/trufflehog-actions-scan@v3
        with:
          scanArguments: '--no-filesystem-clone'
