on:
  pull_request:
    branches:
      - 'develop'

jobs:
  secret-search-job:
    runs-on: 'ubuntu-latest'
    name: Job to scan for secrets
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Execute secret-search
        id: secret-search
        uses: Hacks4Snacks/secret-search@main
        with:
          fail-on-error: 'false' # Run even if secrets are found to report results

      - name: Annotate results in PR
        if: ${{ steps.secret-search.outputs.has-secrets == 'true' }} # Conditional based on scan results
        run: |
          echo "::error::Secrets detected in the codebase. Review the scan results."

      - name: Add PR comment with scan results
        if: ${{ steps.secret-search.outputs.has-secrets == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Secrets were detected in the pull request. Please review them carefully." | gh pr comment --body -
